<?php
/**
 * @copyright Copyright © 2020 CreenSight. All rights reserved.
 * @author CreenSight Development Team <magento@creensight.com>
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $flags = $block->getStoreViewFlag(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <?php if (isset($flags[$block->getCurrentStoreId()]) && !empty($flags[$block->getCurrentStoreId()])) : ?>
                        <?php $currentFlag = $flags[$block->getCurrentStoreId()]; ?>
                         <span class="flag">
                            <img class="flag-image"
                                style="height: <?= $currentFlag['height'] ?>px; width: <?= $currentFlag['width']; ?>px; vertical-align: middle;"
                                src="<?= /* @noEscape */ $currentFlag['image'] ?>"
                                title="<?= $block->escapeHtml($block->getStoreName()) ?>"
                                alt=" <?= $block->escapeHtml($block->getStoreName()) ?>" />
                        </span>
                    <?php endif; ?>
                    <span>
                        <?= (isset($flags[$block->getCurrentStoreId()]) && !empty($flags[$block->getCurrentStoreId()]) && ($flags[$block->getCurrentStoreId()]['hide_store_name'])) ? '' : $block->escapeHtml($block->getStoreName()) ?>
                    </span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown"
                style="<?= (isset($flags[$block->getCurrentStoreId()]) && !empty($flags[$block->getCurrentStoreId()]) && ($flags[$block->getCurrentStoreId()]['hide_store_name']))? 'min-width:auto': ''; ?>" >
                <?php foreach ($block->getStores() as $_lang) : ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                <?php if (isset($flags[$_lang->getId()]) && !empty($flags[$_lang->getId()])) : ?>
                                    <?php $flag = $flags[$_lang->getId()]; ?>
                                    <span class="flag">
                                        <img class="flag-image"
                                             style="height: <?= $flag['height'] ?>px; width: <?= $flag['width']; ?>px; vertical-align: middle;"
                                             src="<?= /* @noEscape */ $flag['image'] ?>"
                                             title="<?= $block->escapeHtml($_lang->getName()) ?>"
                                             alt="<?= $block->escapeHtml($_lang->getName()) ?>"/>
                                    </span>
                                <?php endif; ?>
                                <?= (isset($flags[$block->getCurrentStoreId()]) && !empty($flags[$block->getCurrentStoreId()]) && ($flags[$block->getCurrentStoreId()]['hide_store_name'])) ? '' : $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
